### ISSUE TITLE
is it still early stage

### ISSUE THREAD

**Issue by ugintl** [KeruyCRM/KeruyCRM#1]
is it still in its early stage?

**Comment by KeruyPHP** [comment]
There is a stable version https://github.com/KeruyCRM/KeruyCRM/tree/1.0

**Comment by ugintl** [comment]
@KeruyCRM How to install in english?

**Comment by ugintl** [comment]
@KeruyCRM ok in the url, I replaced "ukranian" with "english" like this `http://keruycrm.test/install/index.php?step=checking_environment&lng=english`. It worked, but I see this screen now 
![keruy](https://user-images.githubusercontent.com/12570802/193552777-8e13e8bd-ca59-409a-983d-bab65ebfae8c.jpeg)
